fixed installation of sicp racket package

diff --git a/Dockerfiles/Dockerfile.racket-sicp b/Dockerfiles/Dockerfile.racket-sicp
--- a/Dockerfiles/Dockerfile.racket-sicp
+++ b/Dockerfiles/Dockerfile.racket-sicp
@@ -9,4 +9,6 @@ RUN sudo dnf install -y ripgrep neovim gcc
 
 # Install racket and the sicp package to be able to run the code in the book as-is.
 RUN sudo dnf install -y openssl-devel racket-minimal
-RUN raco pkg install --auto sicp
+RUN raco pkg install --auto sicp \
+    || raco pkg install --auto sicp \
+    || echo "this command has to be run twice to work and it will return an error each time"
